# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# [TEMPLATE] Build webrtc.lib for Desktop (Win32) platform

parameters:
- name: buildAgent
  type: string
  default: ''
- name: buildArch
  type: string
  default: ''
  values:
  - x86
  - x64
- name: buildConfig
  type: string
  default: ''
  values:
  - Debug
  - Release

jobs:

# Build webrtc.lib (core Google implementation)
- job: libwebrtc_Win32_${{parameters.buildArch}}_${{parameters.buildConfig}}
  timeoutInMinutes: 360
  pool:
    name: ${{parameters.buildAgent}}
    demands:
    - msbuild
  variables:
    buildTriple: Win32-${{parameters.buildArch}}-${{parameters.buildConfig}}
    projectRoot: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/'
  steps:

  # Install Python 2.7.17 and select as default
  - template: 'steps-install-python2x.yaml'
    parameters:
      tempFolder: '$(Build.BinariesDirectory)\py27'
      pythonVersion: '2.7.17'

  # Checkout
  - checkout: self
    submodules: recursive
    clean: true

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: Map script variables
    inputs:
      targetType: filePath
      filePath: tools/ci/mapVariables.ps1
      arguments: 'Win32 ${{parameters.buildArch}} ${{parameters.buildConfig}}'

  # Prepare build
  - task: PythonScript@0
    displayName: 'Prepare build'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a prepare -t webrtc -p win --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper --cpp17'
      failOnStderr: false

  # Clean-up unused files checked out by the Google scripts but not used in the build
  - script: |
      del /F /S /Q "depot_tools/external_bin/gsutil"
      del /F /S /Q "chromium/third_party/protobuf/java"
      del /F /S /Q "chromium/tools/android"
      del /F /S /Q "chromium/tools/code_coverage"
    workingDirectory: 'external/webrtc-uwp-sdk/webrtc/xplatform'
    displayName: 'Clean-up unused files'

  # Run component detection
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  # Build webrtc.lib
  - task: PythonScript@0
    displayName: 'Build webrtc.lib ($(buildTriple))'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a build -t webrtc -p win --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper --cpp17'
      failOnStderr: false
    timeoutInMinutes: 120

  # Stage artifact files for publish
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}'
      Contents: |
        webrtc.lib
        pdbs\**\*.pdb
      TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
      CleanTargetFolder: true
      flattenFolders: false
      preserveTimestamp: true
    timeoutInMinutes: 15

  # List content of artifacts folder
  - powershell: |
      foreach ($f in $(Get-ChildItem -Path $(Build.ArtifactStagingDirectory)/drop -Recurse)) {
        Write-Host $f.FullName
      }
    displayName: 'List artifacts to publish'
    timeoutInMinutes: 5

  # Publish artifacts
  - task: PublishPipelineArtifact@0
    displayName: 'Publish ($(buildTriple))'
    inputs:
      artifactName: 'libwebrtc_$(buildTriple)'
      targetPath: '$(Build.ArtifactStagingDirectory)/drop'
    timeoutInMinutes: 15
