# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# [TEMPLATE] Build webrtc.lib for UWP platform

parameters:
- name: buildAgent
  type: string
  default: ''
- name: buildArch
  type: string
  default: ''
  values:
  - x86
  - x64
  - ARM
  - ARM64
- name: buildConfig
  type: string
  default: ''
  values:
  - Debug
  - Release
- name: publishWinRtHeaders
  type: boolean
  default: false

jobs:

# Compile webrtc.lib (core Google implementation)
- job: libwebrtc_UWP_${{parameters.buildArch}}_${{parameters.buildConfig}}
  timeoutInMinutes: 360
  pool:
    name: ${{parameters.buildAgent}}
    demands:
    - msbuild
  variables:
    buildTriple: UWP-${{parameters.buildArch}}-${{parameters.buildConfig}}
    projectRoot: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/'
  steps:

  # Display memory at start
  - powershell: |
      Get-WmiObject WIN32_PROCESS | Sort-Object -Property ws -Descending | Select-Object -first 5 ProcessID,Name,WS

  # Install Python 2.7.17 and select as default
  - template: 'steps-install-python2x.yaml'
    parameters:
      tempFolder: '$(Build.BinariesDirectory)\py27'
      pythonVersion: '2.7.17'

  # Checkout
  - checkout: self
    submodules: recursive
    clean: true

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: Map script variables
    inputs:
      targetType: filePath
      filePath: tools/ci/mapVariables.ps1
      arguments: 'UWP ${{parameters.buildArch}} ${{parameters.buildConfig}}'

  # # Clean IDLs
  # - task: PythonScript@0
  #   displayName: Clean IDLs
  #   inputs:
  #     scriptSource: 'filePath'
  #     scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
  #     arguments: '-a clean --cleanOptions cleanidls'
  #     failOnStderr: false

  # # Restore any NuGet package (C++/WinRT, ...)
  # - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
  #   displayName: 'Restore NuGet packages for Org.WebRtc'
  #   inputs:
  #     command: restore
  #     restoreSolution: '$(projectRoot)Org.WebRtc.Universal/packages.config'
  #     restoreDirectory: ../../../solutions/packages
  #   timeoutInMinutes: 10

  # Prepare build
  - task: PythonScript@0
    displayName: 'Prepare build'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a prepare -t webrtc -p winuwp --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper --cpp17'
      failOnStderr: false

  # Clean-up unused files
  - script: |
      del /F /S /Q "depot_tools/external_bin/gsutil"
      del /F /S /Q "chromium/third_party/protobuf/java"
      del /F /S /Q "chromium/tools/android"
      del /F /S /Q "chromium/tools/code_coverage"
    workingDirectory: 'external/webrtc-uwp-sdk/webrtc/xplatform'
    displayName: 'Clean-up unused files'

  # Run component detection
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  # Build webrtc.lib
  - task: PythonScript@0
    displayName: 'Build webrtc.lib ($(buildTriple))'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a build -t webrtc -p winuwp --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper --cpp17'
      failOnStderr: false
    timeoutInMinutes: 120

  # # Build the UWP wrapper
  # - task: MSBuild@1
  #   displayName: 'Build Org.WebRTC WinRT wrappers ($(buildTriple))'
  #   inputs:
  #     solution: '$(projectRoot)Org.WebRtc.Universal/Org.WebRtc.vcxproj'
  #     msbuildVersion: '15.0'
  #     msbuildArchitecture: x64
  #     platform: ${{parameters.buildArch}}
  #     configuration: ${{parameters.buildConfig}}
  #   timeoutInMinutes: 180

  # Stage artifact files for publish
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}'
      Contents: |
        webrtc.lib
        pdbs\**\*.pdb
      TargetFolder: '$(Build.ArtifactStagingDirectory)/drop/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}'
      CleanTargetFolder: true
      flattenFolders: false
      preserveTimestamp: true
    timeoutInMinutes: 15
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/sdk/windows/wrapper'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/drop/webrtc-uwp-sdk/webrtc/xplatform/webrtc/sdk/windows/wrapper'
      CleanTargetFolder: true
      flattenFolders: false
      preserveTimestamp: true
    timeoutInMinutes: 15
  # - task: CopyFiles@2
  #   inputs:
  #     SourceFolder: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.Universal/Build/Output/Org.WebRtc/${{parameters.buildConfig}}/${{parameters.buildArch}}'
  #     Contents: |
  #       Org.WebRtc.dll
  #       Org.WebRtc.pdb
  #     TargetFolder: '$(Build.ArtifactStagingDirectory)/drop/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.Universal/Build/Output/Org.WebRtc/${{parameters.buildConfig}}/${{parameters.buildArch}}'
  #     CleanTargetFolder: true
  #     flattenFolders: false
  #     preserveTimestamp: true
  #   timeoutInMinutes: 15
  # - task: CopyFiles@2
  #   inputs:
  #     SourceFolder: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.WrapperGlue.Universal/Build/Output/Org.WebRtc.WrapperGlue/${{parameters.buildConfig}}/${{parameters.buildArch}}'
  #     Contents: |
  #       Org.WebRtc.WrapperGlue.lib
  #       Org.WebRtc.WrapperGlue.pdb
  #     TargetFolder: '$(Build.ArtifactStagingDirectory)/drop/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.WrapperGlue.Universal/Build/Output/Org.WebRtc.WrapperGlue/${{parameters.buildConfig}}/${{parameters.buildArch}}'
  #     CleanTargetFolder: true
  #     flattenFolders: false
  #     preserveTimestamp: true
  #   timeoutInMinutes: 15

  # List content of artifacts folder
  - powershell: |
      foreach ($f in $(Get-ChildItem -Path $(Build.ArtifactStagingDirectory)/drop -Recurse)) {
        Write-Host $f.FullName
      }
    displayName: 'List artifacts to publish'
    timeoutInMinutes: 5

  # Publish artifacts
  - task: PublishPipelineArtifact@0
    displayName: 'Publish ($(buildTriple))'
    inputs:
      artifactName: 'libwebrtc_$(buildTriple)'
      targetPath: '$(Build.ArtifactStagingDirectory)/drop'
    timeoutInMinutes: 15

  # Display memory at end
  - powershell: |
      Get-WmiObject WIN32_PROCESS | Sort-Object -Property ws -Descending | Select-Object -first 5 ProcessID,Name,WS

# Build Org.WebRtc wrapper
- job: orgwebrtc_UWP_${{parameters.buildArch}}_${{parameters.buildConfig}}
  dependsOn: libwebrtc_UWP_${{parameters.buildArch}}_${{parameters.buildConfig}}
  timeoutInMinutes: 360
  pool:
    name: ${{parameters.buildAgent}}
    demands:
    - msbuild
  variables:
    buildTriple: UWP-${{parameters.buildArch}}-${{parameters.buildConfig}}
    projectRoot: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/'
  steps:

  # Display memory at start
  - powershell: |
      Get-WmiObject WIN32_PROCESS | Sort-Object -Property ws -Descending | Select-Object -first 5 ProcessID,Name,WS

  # Install Python 2.7.17 and select as default
  - template: 'steps-install-python2x.yaml'
    parameters:
      tempFolder: '$(Build.BinariesDirectory)\py27'
      pythonVersion: '2.7.17'

  # Checkout
  - checkout: self
    submodules: recursive
    clean: true

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: Map script variables
    inputs:
      targetType: filePath
      filePath: tools/ci/mapVariables.ps1
      arguments: 'UWP ${{parameters.buildArch}} ${{parameters.buildConfig}}'

  # Clean IDLs
  - task: PythonScript@0
    displayName: Clean IDLs
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a clean --cleanOptions cleanidls'
      failOnStderr: false

  # Restore any NuGet package (C++/WinRT, ...)
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
    displayName: 'Restore NuGet packages for Org.WebRtc'
    inputs:
      command: restore
      restoreSolution: '$(projectRoot)Org.WebRtc.Universal/packages.config'
      restoreDirectory: ../../../solutions/packages
    timeoutInMinutes: 10

  # Prepare build
  - task: PythonScript@0
    displayName: 'Prepare build'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a prepare -t webrtc -p winuwp --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper --cpp17'
      failOnStderr: false

  # Clean-up unused files
  - script: |
      del /F /S /Q "depot_tools/external_bin/gsutil"
      del /F /S /Q "chromium/third_party/protobuf/java"
      del /F /S /Q "chromium/tools/android"
      del /F /S /Q "chromium/tools/code_coverage"
    workingDirectory: 'external/webrtc-uwp-sdk/webrtc/xplatform'
    displayName: 'Clean-up unused files'

  # Download libwebrtc from previous job
  - task: DownloadPipelineArtifact@2
    displayName: 'Download libwebrtc UWP-${{parameters.buildArch}}-${{parameters.buildConfig}}'
    inputs:
      source: 'current'
      artifact: 'libwebrtc_UWP-${{parameters.buildArch}}-${{parameters.buildConfig}}'
      patterns: |
        webrtc-uwp-sdk\webrtc\xplatform\webrtc\OUTPUT\**\webrtc.lib
        webrtc-uwp-sdk\webrtc\xplatform\webrtc\OUTPUT\**\pdbs\**\*.pdb
      path: 'external'
  - task: DownloadPipelineArtifact@2
    displayName: 'Download libwebrtc UWP-${{parameters.buildArch}}-${{parameters.buildConfig}}'
    inputs:
      source: 'current'
      artifact: 'libwebrtc_UWP-${{parameters.buildArch}}-${{parameters.buildConfig}}'
      patterns: |
        webrtc-uwp-sdk/webrtc/xplatform/webrtc/sdk/windows/wrapper/**
      path: 'external'

  # List restored files
  - powershell: |
      foreach ($f in $(Get-ChildItem -Path external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT -Recurse)) {
        Write-Host $f.FullName
      }
    displayName: 'List restored files'
    timeoutInMinutes: 5
  - powershell: |
      foreach ($f in $(Get-ChildItem -Path webrtc-uwp-sdk/webrtc/xplatform/webrtc/sdk/windows/wrapper -Recurse)) {
        Write-Host $f.FullName
      }
    displayName: 'List restored files'
    timeoutInMinutes: 5

  # Run component detection
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  # Display memory before build
  - powershell: |
      Get-WmiObject WIN32_PROCESS | Sort-Object -Property ws -Descending | Select-Object -first 5 ProcessID,Name,WS

  # Build the UWP wrapper
  - task: MSBuild@1
    displayName: 'Build Org.WebRTC WinRT wrappers ($(buildTriple))'
    inputs:
      solution: '$(projectRoot)Org.WebRtc.Universal/Org.WebRtc.vcxproj'
      msbuildVersion: '15.0'
      msbuildArchitecture: x64
      platform: ${{parameters.buildArch}}
      configuration: ${{parameters.buildConfig}}
    timeoutInMinutes: 180

  # Display memory after build
  - powershell: |
      Get-WmiObject WIN32_PROCESS | Sort-Object -Property ws -Descending | Select-Object -first 5 ProcessID,Name,WS

  # Stage artifact files for publish
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.Universal/Build/Output/Org.WebRtc/${{parameters.buildConfig}}/${{parameters.buildArch}}'
      Contents: |
        Org.WebRtc.dll
        Org.WebRtc.pdb
      TargetFolder: '$(Build.ArtifactStagingDirectory)/drop/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.Universal/Build/Output/Org.WebRtc/${{parameters.buildConfig}}/${{parameters.buildArch}}'
      CleanTargetFolder: true
      flattenFolders: false
      preserveTimestamp: true
    timeoutInMinutes: 15
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.WrapperGlue.Universal/Build/Output/Org.WebRtc.WrapperGlue/${{parameters.buildConfig}}/${{parameters.buildArch}}'
      Contents: |
        Org.WebRtc.WrapperGlue.lib
        Org.WebRtc.WrapperGlue.pdb
      TargetFolder: '$(Build.ArtifactStagingDirectory)/drop/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.WrapperGlue.Universal/Build/Output/Org.WebRtc.WrapperGlue/${{parameters.buildConfig}}/${{parameters.buildArch}}'
      CleanTargetFolder: true
      flattenFolders: false
      preserveTimestamp: true
    timeoutInMinutes: 15

  # List content of artifacts folder
  - powershell: |
      foreach ($f in $(Get-ChildItem -Path $(Build.ArtifactStagingDirectory)/drop -Recurse)) {
        Write-Host $f.FullName
      }
    displayName: 'List artifacts to publish'
    timeoutInMinutes: 5

  # Publish artifacts
  - task: PublishPipelineArtifact@0
    displayName: 'Publish ($(buildTriple))'
    inputs:
      artifactName: 'orgwebrtc_$(buildTriple)'
      targetPath: '$(Build.ArtifactStagingDirectory)/drop'
    timeoutInMinutes: 15

  # Display memory at end
  - powershell: |
      Get-WmiObject WIN32_PROCESS | Sort-Object -Property ws -Descending | Select-Object -first 5 ProcessID,Name,WS
