# MixedReality-WebRTC build pipeline for CI
# Build the project's libraries as needed

# TEMP - Disable branch and PR triggers
# Note that trigger:none is not enough, because it is not enforced when
# a new YAML file is pushed.
trigger:
  branches:
    exclude: *
  paths:
    exclude: *
pr:
  branches:
    exclude: *
  paths:
    exclude: *

# Give a unique name to the build each time it runs
name: ci-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:r)

jobs:
- template: templates/cpp.yaml
  parameters:
    buildPlatform: 'Win32'
    buildArch: 'x64'
    buildConfig: 'Release'
- template: templates/cpp.yaml
  parameters:
    buildPlatform: 'UWP'
    buildArch: 'x64'
    buildConfig: 'Release'
# - template: templates/cpp.yaml
#   parameters:
#     buildPlatform: 'UWP'
#     buildArch: 'ARM'
#     buildConfig: 'Release'
