# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# MixedReality-WebRTC build pipeline for project dependencies

# Trigger CI on push changes to external/ only
trigger:
  branches:
    include:
    - master
    - release/*
    exclude:
    - docs/*
  paths:
    include:
    - external

# Do not trigger CI on PRs
pr: none

# Give a unique name to the build each time it runs
name: deps-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:r)

stages:

# # Build libwebrtc
# - stage: build
#   displayName: 'Build'
#   jobs:

#   # Build libwebrtc.so for Android
#   - template: templates/jobs-build-libwebrtc-android.yaml
#     parameters:
#       buildConfig: 'Debug'
#   # - template: templates/jobs-libwebrtc-android.yaml
#   #   parameters:
#   #     buildConfig: 'Release'

#   # Build webrtc.lib for Windows Desktop
#   - template: templates/jobs-build-libwebrtc-win32.yaml
#     parameters:
#       buildAgent: 'Hosted VS2017'
#       buildArch: 'x86'
#       buildConfig: 'Debug'
#   # - template: templates/jobs-build-libwebrtc-win32.yaml
#   #   parameters:
#   #     buildAgent: 'Hosted VS2017'
#   #     buildArch: 'x86'
#   #     buildConfig: 'Release'
#   # - template: templates/jobs-build-libwebrtc-win32.yaml
#   #   parameters:
#   #     buildAgent: 'Hosted VS2017'
#   #     buildArch: 'x64'
#   #     buildConfig: 'Debug'
#   # - template: templates/jobs-build-libwebrtc-win32.yaml
#   #   parameters:
#   #     buildAgent: 'Hosted VS2017'
#   #     buildArch: 'x64'
#   #     buildConfig: 'Release'

#   # Build webrtc.lib for Windows UWP
#   - template: templates/jobs-build-libwebrtc-uwp.yaml
#     parameters:
#       buildAgent: 'Hosted VS2017'
#       buildArch: 'x86'
#       buildConfig: 'Debug'

# Publish libwebrtc
- stage: publish
  displayName: 'Publish'
  #dependsOn: build
  jobs:
  - job: publish
    timeoutInMinutes: 60
    pool:
      name: 'Hosted VS2017'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'tools/ci/GetDepsPackageSuffix.ps1'
        arguments: '-GitBranch $(Build.SourceBranch) -GitCommitSha1 $(Build.SourceVersion)'
        failOnStderr: false
        pwsh: true
    - task: DownloadPipelineArtifact@2
      displayName: 'Download libwebrtc android-arm64-Debug'
      inputs:
        source: 'current'
        artifact: 'libwebrtc_android-arm64-Debug'
        path: '$(Build.ArtifactStagingDirectory)/libwebrtc/android/arm64/Debug'
    - task: DownloadPipelineArtifact@2
      displayName: 'Download libwebrtc Win32-x86-Debug'
      inputs:
        source: 'current'
        artifact: 'libwebrtc_Win32-x86-Debug'
        path: '$(Build.ArtifactStagingDirectory)/libwebrtc'
    - task: DownloadPipelineArtifact@2
      displayName: 'Download libwebrtc UWP-x86-Debug'
      inputs:
        source: 'current'
        artifact: 'libwebrtc_UWP-x86-Debug'
        path: '$(Build.ArtifactStagingDirectory)/libwebrtc'
    - powershell: |
        foreach ($f in $(Get-ChildItem -Path $(Build.ArtifactStagingDirectory)/libwebrtc -Recurse)) {
          Write-Host $f.FullName
        }
      displayName: 'List restored external/'
      timeoutInMinutes: 5
    - task: UniversalPackages@0
      displayName: Publish
      inputs:
        command: publish
        publishDirectory: '$(Build.ArtifactStagingDirectory)/libwebrtc'
        vstsFeedPublish: 'MixedReality-WebRTC-CI/mr-webrtc'
        vstsFeedPackagePublish: 'libwebrtc'
        packagePublishDescription: 'Prebuilt libwebrtc from branch $(Build.SourceBranch) at $(Build.SourceVersion)'
        versionOption: custom
        versionPublish: '$(DepsPackageVersion)'
