# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# MixedReality-WebRTC release pipeline for mrwebrtc on Windows.
# This builds libwebrtc and mrwebrtc, then create signed NuGet packages
# of mrwebrtc (Microsoft.MixedReality.WebRTC.Native.*.nupkg).

# Disable branch and PR triggers
trigger: none
pr: none

# Give a unique name to the build each time it runs
name: release-mrwebrtc-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:r)

parameters:
- name: buildAgent
  type: string
  default: ''
- name: packageAgent
  type: string
  default: ''
- name: nugetPackageVersion
  type: string
  default: '0.0.1-preview.1'

stages:

# Build for all build variants.
# This is done as a separate stage from packing to ensure all builds
# for all variants succeeded before starting to pack anything for release.
- stage: build
  displayName: 'Build'
  jobs:

  # Build all variants of mrwebrtc.dll for Windows Desktop
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'Win32'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x86'
      buildConfig: 'Debug'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'Win32'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x86'
      buildConfig: 'Release'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'Win32'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x64'
      buildConfig: 'Debug'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'Win32'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x64'
      buildConfig: 'Release'

  # Build all variants of mrwebrtc.dll for Windows UWP
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'UWP'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x86'
      buildConfig: 'Debug'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'UWP'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x86'
      buildConfig: 'Release'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'UWP'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x64'
      buildConfig: 'Debug'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'UWP'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x64'
      buildConfig: 'Release'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'UWP'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'ARM'
      buildConfig: 'Debug'
  - template: templates/jobs-mrwebrtc-release-build.yaml
    parameters:
      buildPlatform: 'UWP'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'ARM'
      buildConfig: 'Release'

  # Build all variants of Microsoft.MixedReality.WebRTC.dll
  - template: templates/jobs-cslib-release-build.yaml
    parameters:
      buildAgent: '${{parameters.buildAgent}}'

# Pack the NuGet packages
- stage: pack
  dependsOn: build
  displayName: 'Pack'
  jobs:

  # Package mrwebrtc (Desktop)
  - template: templates/jobs-mrwebrtc-release-pack.yaml
    parameters:
      packagePlatform: 'Desktop'
      packageAgent: '${{parameters.packageAgent}}'
      nugetPackageVersion: '${{parameters.nugetPackageVersion}}'

  # Package mrwebrtc (UWP)
  - template: templates/jobs-mrwebrtc-release-pack.yaml
    parameters:
      packagePlatform: 'UWP'
      packageAgent: '${{parameters.packageAgent}}'
      nugetPackageVersion: '${{parameters.nugetPackageVersion}}'

  # Package C# library (Desktop)
  - template: templates/jobs-cslib-release-pack.yaml
    parameters:
      packagePlatform: 'Desktop'
      packageAgent: '${{parameters.packageAgent}}'
      nugetPackageVersion: '${{parameters.nugetPackageVersion}}'

  # Package C# library (UWP)
  - template: templates/jobs-cslib-release-pack.yaml
    parameters:
      packagePlatform: 'UWP'
      packageAgent: '${{parameters.packageAgent}}'
      nugetPackageVersion: '${{parameters.nugetPackageVersion}}'
