# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# MixedReality-WebRTC release pipeline for mrwebrtc on Windows.
# This builds libwebrtc and mrwebrtc, then create signed NuGet packages
# of mrwebrtc (Microsoft.MixedReality.WebRTC.Native.*.nupkg).

# Disable branch and PR triggers
trigger: none
pr: none

# Give a unique name to the build each time it runs
name: release-mrwebrtc-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:r)

parameters:
- name: buildAgent
  type: string
  default: 'Hosted VS2017' # vs2017-win2016
- name: nugetPackageVersion
  type: string
  default: '0.0.1-preview.1'

stages:

# Build all Release variants of webrtc.lib and mrwebrtc.dll
- stage: build
  displayName: 'Build'
  jobs:
  # - template: templates/jobs-mrwebrtc-release.yaml
  #   parameters:
  #     buildPlatform: 'Win32'
  #     buildAgent: '${{parameters.buildAgent}}'
  #     buildArch: 'x86'
  #     buildConfig: 'Debug'
  - template: templates/jobs-mrwebrtc-release.yaml
    parameters:
      buildPlatform: 'Win32'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'x64'
      buildConfig: 'Debug'
  # - template: templates/jobs-mrwebrtc-release.yaml
  #   parameters:
  #     buildPlatform: 'UWP'
  #     buildAgent: '${{parameters.buildAgent}}'
  #     buildArch: 'x86'
  #     buildConfig: 'Debug'
  # - template: templates/jobs-mrwebrtc-release.yaml
  #   parameters:
  #     buildPlatform: 'UWP'
  #     buildAgent: '${{parameters.buildAgent}}'
  #     buildArch: 'x64'
  #     buildConfig: 'Debug'
  - template: templates/jobs-mrwebrtc-release.yaml
    parameters:
      buildPlatform: 'UWP'
      buildAgent: '${{parameters.buildAgent}}'
      buildArch: 'ARM'
      buildConfig: 'Debug'

# Compile Microsoft.MixedReality.WebRTC.dll
- stage: build_cs
  dependsOn: build
  displayName: 'Build C# library'
  jobs:
  - template: templates/jobs-cs-build.yaml
    parameters:
      buildAgent: '${{parameters.buildAgent}}'
      buildConfig: 'Release'
      publishArtifacts: true
      withTesting: false

# Package library and samples
- stage: publish
  dependsOn: build_cs
  displayName: 'Publish'
  jobs:
  - template: templates/jobs-unity-package.yaml
    parameters:
      buildAgent: '${{parameters.buildAgent}}'
      npmPackageVersion: '${{parameters.npmPackageVersion}}'
